export const message= {
    sucess:{
        UserCreated:"¡Usuario creado con éxito!",
        CompanyCreated:"Empresa creado con éxito!",
        UserLogged:"¡Usuario iniciado con éxito!",
        CompanyLogged:"¡Empresa/Operador iniciado con éxito!",
        EmailSent:"El correo electrónico se ha enviado correctamente. Compruebe su correo electrónico.",
        PwdChanged:"¡Su contraseña ha sido modificada correctamente!",
        TokenRefreshed:"El token se ha actualizado correctamente.",
        UserAuthorized:"User is authorized.",
        UserLoggedOut:"¡Usuario cerrado sesión con éxito!",
        ProfileEdited:"¡Perfil actualizado con éxito!",
        JobPublicated:"¡Oferta de trabajo publicada con éxito!",
        JobEdited:"¡Oferta de trabajo editado con éxito!",
        GenericSuccess:"El cambio guardado con exito!",
        JobSaved:"Trabajo aplicado con exito! Buena suerte!:)",
        StatusUpdated:"Estado del candiadto actualizado con exito!",
        OperatorCreated:"¡Operador creado con éxito!",
        OperatorDeleted:"¡Operador eliminado con éxito!",
        OperatorModified:"¡Operador modificado con éxito!"
    },
    error:{
        notFull:"Por favor, rellene todos los campos.",
        invalidEmial: "¡El correo electrónico proporcionado no es válido!",
        notMatchPwd:"¡Las contraseñas no coinciden!",
        onlyLetterName: "¡El nombre sólo puede tener letras!",
        onlyLetterSpace:"Por favor, ¡revisa su apellidos!",
        alreadyExist:"El correo electrónico ya existe, intente Iniciar sesión",
        notFoundUser:"El correo o la contraseña incorrecta. Inténtelo de nuevo." ,
        pwdIncorrect:"La contraseña es incorrecta, inténtelo de nuevo.",
        genericError:"Something is wrong...",
        notFoundEmail:"No existe ningún usuario con el correo proporcionado. Por favor, revise o intente registrarse.",
        notFoundEmailCompany:"No existe ningúna Empresa/Operador con el correo proporcionado. Por favor, revise o intente registrarse.",
        pwdCantChange:"No se puede cambiar la contraseña, inténtelo más tarde.",
        passwordRestrict:"La contraseña debe contener al menos 8 caracteres, 1 letra minúscula, 1 mayúscula, 1 número y 1 carácter especial.",
        noToken:"No hay permiso para continuar el proceso, por favor, reinicie el proceso.",
        invalidToken:"El permiso de restablecer contraseña se ha expirado, por favor, reinicie el proceso.",
        notValidCif:"¡El C.I.F proporcionado no es válido!",
        logOutError:"¡Ocurrido error en cerrar sesión!",
        profileLoadError:"¡Ha ocurrido un error al cargar perfil del usuario!",
        profileEditError:"¡Ha ocurrido un error al editar perfil del usuario!",
        jobEditError:"¡Ha ocurrido un error la oferta del trabajo!",
        companyProfileEditError:"¡Ha ocurrido un error al editar perfil de la empresa!",
        jobsLoadError:"¡Ha ocurrido un error al cargar las ofertas de trabajo de la empresa!",
        jobPublicateError:"¡Ha ocurrido un error al publicar la oferta del trabajo!",
        jobLoadError:"¡Ha ocurrido un error al cargar la oferta del trabajo!",
        saveJobError:"¡Ha ocurrido un error al guardar la oferta del trabajo!",
        JobApplyError: "¡Ha ocurrido un error al aplicar la oferta del trabajo!",
        candiateLoadError:"¡Ha ocurrido un error al cargar los candidatos de la oferta del trabajo!",
        statusUpdateError:"¡Ha ocurrido un error al actualizar el estado de candidato en la oferta del trabajo!",
        operatorLoadError:"¡Ha ocurrido un error al iniciar sesión como operator!",
    }
}